backend:
  name: github
  repo: devinhalladay/body-without-organs # Path to your GitHub repository
  branch: new # Branch to update (master by default)

media_folder: "source/assets/images" # Folder where user uploaded files should go
public_folder: "/assets/images"

collections: # A list of collections the CMS should be able to edit
  - name: "item" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Item" # Used in the UI, ie.: "New Post"
    folder: "source/terms" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    extension: ".html.md"
    format: "frontmatter"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string", required: false, tagname: "h1"}
      - {label: 'Image', name: 'image', widget: 'image', required: false, tagname: ''}
      - {
          label: "Tags",
          name: "tags",
          widget: "select",
          multiple: true,
          options: [
            "Crisis",
            "Modernity",
            "Power",
            "Aesthetics",
            "Ideology",
            "Software",
            "Politics",
            "Product Design",
            "Image",
            "Identity",
            "Simulation",
            "Responsibility",
            "Design",
            "Responsible Objects",
            "Ontology",
            "Public Domain",
            "Open Source",
            "Materialism",
            "Dialectics",
            "Deconstruction",
            "Technics",
            "Immaterial Labor",
            "Labor",
            "Spirit",
            "Metaphysics",
            "Philosophy",
            "Democracy",
            "Marxism",
            "Marxist Aesthetics",
            "Apparatus",
            "Interface",
            "Responsibility",
            "Phenomenology",
            "Ecology",
            "Archeology",
            "Mercurial",
            "Power",
            "Violence",
            "Class",
            "Designer",
            "Designed",
            "Acceleration",
            "Critical Theory",
            "Praxis",
            "Sustainibility",
            "Poetics",
            "Schizophrenia",
            "Capitalism",
            "Rhizome",
            "Utopia",
            "Depth",
            "Liberation",
          ]
        }
      - {label: "Body", name: "body", widget: "markdown", required: false}
